const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT';
const UPDATE_STUDENT = 'UPDATE_STUDENT';
const DELETE_STUDENT = 'DELETE_STUDENT';

export default {
    ADD_NEW_STUDENT,
    UPDATE_STUDENT,
    DELETE_STUDENT
}